Typo fix and minor changes

diff --git a/benchmarks/motorbike/Mesh b/benchmarks/motorbike/Mesh
--- a/benchmarks/motorbike/Mesh
+++ b/benchmarks/motorbike/Mesh
@@ -13,6 +13,7 @@ NPROCS=16
 
 echo "Setting up with $NPROCS procs.  Blockmesh size = $NX x $NY x $NZ"
 
+
 # Check if OpenFOAM is from OpenCFD
 [[ $FOAM_API =~ ^[0-9]{2}(06|12)$ ]] && OPENCFD=1 || OPENCFD=0
 # Specific case when OpenFOAM Foundation version 9/11 and later
@@ -62,17 +63,6 @@ do
  fi
 done
 
-#if [[ $OPENCFD = "1" ]]; then
-# afiles=(
-#  "snappyHexMeshDict"
-#  "meshQualityDict"
-# )
-# if [[ -f "$baseDir/system/$file" ]]; then
-#  echo "Copying $baseDir/system/$file to system/"
-#  cp -f "$baseDir/system/$file" system/
-# fi
-#fi
-
 # Check surfaceFexture extraction executable from different OpenFOAM version
 if [[ -f $baseDir/system/surfaceFeatureExtractDict ]]; then
     surface=$(which surfaceFeatureExtract)
@@ -89,6 +79,7 @@ sed -i "/hex/c\    hex (0 1 2 3 4 5 6 7) (${NX} ${NY} ${NZ}) simpleGrading (1 1 
 # This will limit global number of cell to 50000000(50M)
 # If you need to create mesh larger than 50M, then increase this value
 foamDictionary -entry castellatedMeshControls${scopechar}maxGlobalCells -set "50000000" system/snappyHexMeshDict
+# This is fix for some old OpenCFD distribution
 foamDictionary -entry addLayersControls${scopechar}minMedialAxisAngle -set "90" system/snappyHexMeshDict
 # This will make OpenFOAM start from "startTime" not "latestTime"
 foamDictionary -entry "startFrom" -set "startTime" system/controlDict
@@ -141,5 +132,5 @@ rm -rf processor*
 
 # This is optional. This may improve performance and may cause more unstable result for some cases
 runApplication renumberMesh -constant -overwrite
-[[ $? -ne 0 ]] && echo "reconstructPar* failed"
+[[ $? -ne 0 ]] && echo "renumberMesh failed"
 
